import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlignLeft,
  ArrowUpDown,
  BellRing,
  BookOpen,
  Box,
  Bot,
  Brain,
  Braces,
  Briefcase,
  CalendarDays,
  ChartCandlestick,
  ChartLine,
  ChartNoAxesColumnIncreasing,
  CheckSquare,
  Clock,
  CloudSun,
  CloudUpload,
  Code2,
  Coins,
  CreditCard,
  Database,
  FileArchive,
  FileOutput,
  FileSearch,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  GitBranch,
  Github,
  Gitlab,
  Globe,
  HardDrive,
  Hash,
  Headset,
  Hourglass,
  Image as ImageIcon,
  Inbox,
  KeyRound,
  Languages,
  Link2,
  List,
  Mail,
  MailPlus,
  MapPin,
  Merge,
  MessageCircle,
  MessageSquare,
  MousePointerClick,
  Newspaper,
  NotebookText,
  OctagonAlert,
  Pencil,
  QrCode,
  Reply,
  Repeat,
  Rocket,
  Save,
  Search,
  Send,
  ShoppingBag,
  Shuffle,
  Siren,
  Sparkles,
  Table,
  Terminal,
  Ticket,
  Trello,
  Type,
  UserCheck,
  Users,
  Wallet,
  Webhook,
  Workflow,
  GraduationCap,
  Megaphone,
  Podcast,
  Rss,
  Youtube,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  hand: MousePointerClick,
  webhook: Webhook,
  clock: Clock,
  mail: Mail,
  mailSend: MailPlus,
  slack: MessageSquare,
  github: Github,
  telegram: Send,
  send: Send,
  reply: Reply,
  inbox: Inbox,
  notion: NotebookText,
  sheet: Table,
  table: Table,
  discord: MessageCircle,
  globe: Globe,
  hourglass: Hourglass,
  branch: GitBranch,
  edit: Pencil,
  code: Code2,
  braces: Braces,
  key: KeyRound,
  alert: OctagonAlert,
  userCheck: UserCheck,
  repeat: Repeat,
  flag: Flag,
  merge: Merge,
  terminal: Terminal,
  sparkles: Sparkles,
  bot: Bot,
  template: FileText,
  file: FileText,
  image: ImageIcon,
  users: Users,
  calendar: CalendarDays,
  cloudUpload: CloudUpload,
  creditCard: CreditCard,
  ticket: Ticket,
  list: List,
  checkSquare: CheckSquare,
  messageSquare: MessageSquare,
  gitlab: Gitlab,
  trello: Trello,
  database: Database,
  text: Type,
  filter: Filter,
  sort: ArrowUpDown,
  hash: Hash,
  shuffle: Shuffle,
  brain: Brain,
  weather: CloudSun,
  coins: Coins,
  candlestick: ChartCandlestick,
  chart: ChartLine,
  wallet: Wallet,
  prediction: ChartNoAxesColumnIncreasing,
  mapPin: MapPin,
  rocket: Rocket,
  headset: Headset,
  siren: Siren,
  messageCircle: MessageCircle,
  fileSearch: FileSearch,
  folderOpen: FolderOpen,
  save: Save,
  folder: Folder,
  fileOutput: FileOutput,
  fileArchive: FileArchive,
  alignLeft: AlignLeft,
  bell: BellRing,
  hardDrive: HardDrive,
  briefcase: Briefcase,
  languages: Languages,
  book: BookOpen,
  newspaper: Newspaper,
  rss: Rss,
  youtube: Youtube,
  podcast: Podcast,
  activity: Activity,
  megaphone: Megaphone,
  graduationCap: GraduationCap,
  link: Link2,
  shoppingBag: ShoppingBag,
  search: Search,
  qrcode: QrCode,
  workflow: Workflow,
};

export function NodeIcon({ name, size = 14 }: { name?: string; size?: number }) {
  const C = (name && map[name]) || Box;
  return <C size={size} strokeWidth={1.8} />;
}
